### ISSUE TITLE
[Bug] Visual issue

### ISSUE THREAD

**Issue by fseguraLanding** [dabakovich/react-native-controlled-mentions#99] opened 2022-08-30 15:56 UTC
Hi! I hope you are well.
I'm having a few visual issues with the render function of the MentionInput.
In my case, the trigger character is a '@', and I detected that the renderSuggestions function is rendering 4 times every time I insert a new character. The first time it comes as undefined and that's causing the 'flashing' bug.

Please let me know if you need any other information!

Thanks!

https://user-images.githubusercontent.com/106693705/187484026-9f0b7f4d-3b4d-44a4-93f0-dfc24d7bbe74.mov

**Comment by AnushavanMelon** [comment] 2022-10-28 13:54
In my case keyword:undefined happend when TextInput is multiline.

**Comment by andreirat** [comment] 2023-01-26 07:12
@fseguraLanding @AnushavanGhulyan-melon  I'm having the same issue. I can confirm that it's because of the `multiline` prop. Did you find a fix for this?

**Comment by AnushavanGhulyan-melon** [comment] 2023-02-02 10:44
@andreirat nope

**Comment by marikannantgi** [comment] 2023-02-27 17:29
I am also facing this disturbance Please [fix] this Bug

**Comment by dabakovich** [comment] 2023-07-13 12:20
Hi all! Please refer to the [comment](https://github.com/dabakovich/react-native-controlled-mentions/issues/55#issuecomment-1633995138) in #55.

You are welcome to ask additional questions if they arise.

**Comment by dabakovich** [comment] 2023-09-16 11:43
I'm closing this issue as there have been no further questions.

**Closed by dabakovich** 2023-09-16 11:43 UTC
